name: flutter_maps_application
description: flutter application with google_maps_flutter package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #Google maps connector package
  google_maps_flutter: ^2.4.0

  #fromjson and tojson will automatically generate the function.
  json_annotation: ^4.8.1

  #network konnections
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  #fromjson and tojson will automatically generate the function.
  json_serializable: ^6.7.1

  #build_runner
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

#retrieves the data in the asset file
assets:
  - assets/locations.json
